language: node_js
sudo: required
node_js:
- 4.2.3
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.1.1
before_script:
- npm run setup
services: mongodb
before_deploy:
- ls -ltra
deploy:
  provider: heroku
  app: jellyfish
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: f1my4P0Qqs0mZGti1y8BDx47s/QKQ/QSfSw9UzoJvA3t11+MqdDT/NXS/FZvWlpMuOVCx2bo4JWXxcYpWpoTakFHFjVtzclMRFljxdDQBxPE73O40pjz1AxzmJxuJ4GX5MXSsptbDoEWIje5q+t54VEMVZc319FbH4e8Hzie8n7F3X7rTP0zh1bLdeGMMT5EpIJsHDd1g5iEij4vcE9Ae2QBDBV6HAhX0/0bv924MW5QOqS0ke16I4O6/mg97FmuSVnVYO+e5doeGtqQdRFBa+MHyZQ42D5W3ywRD9DRUtLsmE1/00GLSqer0rRlIrm5uf8oKwaTcmXR8AT+LTNG4/8dF3OABJmu6FbCzhd3afw9EwEdDFrkTt7Qw9H2pdt7cVKhnCP0UJxn3WdTAv2goo1Wi9jz3NDDdXegNPtF0gwAsnhrTHDyQ8jgYXR6Pbw/+wjfvzR/F9jWks5gN1pxT2L2r99/wrnEsmTt8KGivmlCMLr+2QU/14La3iR99/VFmRWyjVgK7VhgTli7njBT6Q/E81DpiXNjO3qWYJ0sf2gdCYHTtuMcj7krenNZbDD+PUUKzDywY3Kuu7Vm5mkdYulelfMsSTePsXU85TQI065MRBwxmWGbULnFg9WzmSJtMtP92rLbLJ7ppws7FYtPqLiSvb1e+9Me2Kqjiba30uk=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  sauce_connect:
    username: Kauabunga
    access_key:
      secure: j3+t1rS28P8YZ2yHDvUJnI2Hcc4pZNJET0zLV3buCpylc0dGnSkvgaHDRT365sjzTRZc4+nzZ7KoYYW7FNtemaX1UOtkwmBbV2Co0+2PQpSa1Gt6fMoNX1MCydacbo6R+UilSu3t8jnk2lypVwvgmVw75PuVpUm/thCrHisU3XU8rBD9B62U0NUXtgAbn88/NV0NU9jxCrPzLtVJMu+SFJ4rZd5U0e7eAXeJtaM1vFyXFT7gOMCtYTts2WL0DMPAhDoaoE/jUM22e7JkmaoLr++g1Z0b/UsOrmLfUtNUgqtu51dejV2qPdN5fMR9AXdCoEh8VfuWZJpszmGiAO35FgHNWx0fPC18w5UviG2FbMhvbiZTLjOxr3rRDjP9ZHt5hgqkwlFlbda/K6dhK9cZXqfgqkACyC5XC8nZCQko0yhvVJfqH59eDbR3MGPs2E8dgHoxt6OHfSmA790vnaqPgsejuqUaIwoYKOouMdlr2d42jdpZfP1A0emLLW0qd72AkbNmp3azW7DyCUPHAidW+wMpTJXzh+KGTQtmBL9OeoEbmzBVkIhB2p/YvVdkjyRQOyqQ7iGul9bO1IGGcQ+djL2pxb4VbN9069A6sOobFjaznipluDgVcymPeOcbhObWca7iLUxjoO+ySHpH/Z265Q8TUlXCaad5HcoBy4vNZyc=
